food_control/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login,logout,password_reset,password_reset_done,password_reset_complete
import alimentus.views
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'^$', alimentus.views.login,name='login'),
    url(r'^login/$', alimentus.views.login,name='login'),
    url(r'^logout$', alimentus.views.log_out,name='logout'),
    url(r'^home/$', alimentus.views.home, name='home'),
    url(r'^signup/$', alimentus.views.signup,name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z]+)/(?P<token>.+)/',alimentus.views.activate,name='activate'),
    url(r'^reset_confirm/(?P<uidb64>[0-9A-Za-z]+)/(?P<uidb65>[0-9A-Za-z]+)$', alimentus.views.reset_confirm, name='reset_confirm'),
    url(r'^password_reset_form/$', alimentus.views.reset, name='reset'),
    url(r'^change_password/$',alimentus.views.change_password,name='change_password'),
    url(r'^ajax/validate_username/$',alimentus.views.validate_username,name='validate_username'),
    url(r'^oauth2/', include('social_django.urls', namespace='social')),
    url(r'^complete_profile/$', alimentus.views.complete_profile, name='complete_profile'),
    url(r'^pacient/$', alimentus.views.complete_profile, name='pacient'),
    url(r'^appointment/(?P<username>.+)$', alimentus.views.citas, name='citas'),
    url(r'^signup_pacient/$', alimentus.views.signup_doctor, name='paciente_doctor'),
    url(r'^add_food/$', alimentus.views.crear_alimento, name='alimento'),
    url(r'^personal_info/$', alimentus.views.personal_info, name='informacion'),
    url(r'^ajax/delete/$', alimentus.views.eliminar_citas, name='eliminar_citas'),
    url(r'^query_pacient/$', alimentus.views.busca_pacientes, name='busca_pacientes'),
    url(r'^food_type/$', alimentus.views.tipo_comida, name='tipo_comida'),
    url(r'^food_register/(?P<tipo>.+)$', alimentus.views.registrar_comida, name='registrar_comida'),
    url(r'^load_food/$', alimentus.views.query_alimentos, name='buscar_alimento'),
    url(r'^food_chart/(?P<username>.+)$', alimentus.views.progress_charts, name='progreso_nutricional')




]

alimentus/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from .models import *
from choices import *


class SignInForm(forms.Form):
    username = forms.CharField(label="Username:", required=True, widget=forms.TextInput(attrs={'required': 'true'}))
    password = forms.CharField(label="Password:",required=True,widget=forms.PasswordInput(attrs={'required': 'true'}))

class Complete_Profile(ModelForm):
    doctor = forms.ModelChoiceField(required=True, queryset=User.objects.all().filter(is_staff=True),widget=forms.Select(attrs={'required': 'True', 'style': 'width:200px'}))
    genero = forms.ChoiceField(required=True, choices=sexo, widget=forms.Select(attrs={'style': 'width:200px'}))
    estatura = forms.DecimalField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Estatura', 'required': 'True,', 'type': 'number', 'style': 'width:80px', 'step': '0.01','min': '0', 'max': '2.50'}))
    peso = forms.DecimalField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Peso ', 'required': 'True,', 'type': 'number', 'style': 'width:75px', 'step': '0.01', 'min': '0', 'max': '500.00'}))
    diabetico = forms.BooleanField(required=False, label=" Diabetico", initial=False)

    class Meta:
        model = Cliente
        fields =['doctor','genero','estatura','peso','diabetico']



class SignUpForm(ModelForm):
    first_name = forms.CharField(required=True,label="Nombre:", widget=forms.TextInput(attrs={'style': 'width:200px','placeholder':'Nombre'}))
    last_name = forms.CharField(required=True,label="Apellidos:", widget=forms.TextInput(attrs={'style': 'width:200px','placeholder':'Apellido'}))
    email = forms.CharField(required=True,label='Email:',widget=forms.EmailInput( attrs={'style':'width:200px','placeholder':'Email'}))
    username= forms.CharField(required=True,label='Username:',widget=forms.TextInput(attrs={'style':'width:200px','placeholder':'Username','aria-describedby':'help-text'}))
    password = forms.CharField(required=True,label='Password:', widget=forms.PasswordInput(attrs={'style': 'width:200px','placeholder':'Password'}))
    re_password= forms.CharField(required=True,label='Re-Password:', widget=forms.PasswordInput(attrs={'style': 'width:200px','placeholder':'Re-password'}))
    doctor = forms.ModelChoiceField(required=True,queryset=User.objects.all().filter(is_staff=True),initial=1,widget=forms.Select(attrs={ 'required': 'True','style':'width:200px'}))
    genero = forms.ChoiceField(label='Género:',required=True,choices=sexo, widget=forms.Select(attrs={'style': 'width:200px'}))
    estatura = forms.DecimalField(required=True,widget=forms.TextInput(attrs={'placeholder':'Estatura','required':'True,','type': 'number','style': 'width:80px','step':'0.01','min':'0','max':'2.50'}))
    peso = forms.DecimalField(required=True,widget=forms.TextInput(attrs={'placeholder':'Peso ','required':'True,','type': 'number','style': 'width:75px','step':'0.01','min':'0','max':'500.00'}))
    diabetico = forms.BooleanField(required=False,label="Diabetico",initial=False)

    class Meta:
        model = Cliente
        fields = ['first_name', 'last_name', 'email','username','password','re_password','doctor','genero','estatura','peso','diabetico']

class InfoForm(ModelForm):
    first_name = forms.CharField(required=True,label="Nombre:", widget=forms.TextInput(attrs={'style': 'width:200px','placeholder':'Nombre'}))
    last_name = forms.CharField(required=True,label="Apellidos:", widget=forms.TextInput(attrs={'style': 'width:200px','placeholder':'Apellido'}))
    email = forms.CharField(required=True,label='Email:',widget=forms.EmailInput( attrs={'style':'width:200px','placeholder':'Email'}))
    username= forms.CharField(disabled=True,required=True,label='Username:',widget=forms.TextInput(attrs={'style':'width:200px','placeholder':'Username','aria-describedby':'help-text'}))
    doctor = forms.ModelChoiceField(required=True,queryset=User.objects.all().filter(is_staff=True),initial=1,widget=forms.Select(attrs={ 'required': 'True','style':'width:200px'}))
    genero = forms.ChoiceField(required=True,choices=sexo, widget=forms.Select(attrs={'style': 'width:200px'}))
    estatura = forms.DecimalField(required=True,widget=forms.TextInput(attrs={'placeholder':'Estatura','required':'True,','type': 'number','style': 'width:80px','step':'0.01','min':'0','max':'2.50'}))
    peso = forms.DecimalField(required=True,widget=forms.TextInput(attrs={'placeholder':'Peso ','required':'True,','type': 'number','style': 'width:75px','step':'0.01','min':'0','max':'500.00'}))
    diabetico = forms.BooleanField(required=False,label="Diabetico",initial=False)

    class Meta:
        model = Cliente
        fields = ['first_name', 'last_name', 'email','username','doctor','genero','estatura','peso','diabetico']


class AlimentoForm(ModelForm):
    nombre=forms.CharField(label="Nombre;",required=True,widget=forms.TextInput(attrs={'style':'width:200px', 'required': 'true','placeholder':'Nombre'}))
    tipo = forms.ChoiceField(required=True,label="Tipo:",choices=Tipo_Alimento,widget=forms.Select(attrs={'style': 'width:200px','placeholder':'Tipo'}))
    calorias = forms.IntegerField(label="Calorias",required=True,widget=forms.TextInput(attrs={'placeholder':'Calorias','required':'True,','type': 'number','style': 'width:80px','min':'0','max':'1000'}))
    grasa = forms.DecimalField(label="Grasa",required=True,widget=forms.TextInput(attrs={'placeholder':'Grasa','required':'True,','type': 'number','style': 'width:80px','step':'0.01','min':'0','max':'100'}))
    proteina = forms.DecimalField(label="Proteina",required=True,widget=forms.TextInput(attrs={'placeholder':'Proteina','required':'True,','type': 'number','style': 'width:80px','step':'0.01','min':'0','max':'100'}))
    agua = forms.DecimalField(label="Agua", required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Agua', 'required': 'True,', 'type': 'number', 'style': 'width:80px', 'step': '0.01',
               'min': '0', 'max': '100'}))

    class Meta:
        model = Alimento
        fields =["nombre","tipo","calorias","grasa","proteina","agua"]


class PasswordResetRequestForm(forms.Form):
    username_password = forms.CharField( required=True,label='Username: ',widget=forms.TextInput( attrs={'style':'width:200px', 'required': 'true','aria-describedby':'id_username_password'}))

class Change_Password(forms.Form):
    password = forms.CharField(required=True,label='Password',widget=forms.PasswordInput(attrs={'style': 'width:200px'}))
    re_password =forms.CharField(required=True,label='Re-Password',widget=forms.PasswordInput(attrs={'style': 'width:200px'}))

class Semana(forms.Form):
    idSemana = forms.CharField(label="",required=False,widget=forms.TextInput(attrs={'style':'width:45px; height:20px; font-size: small;' }))

templates/activate_account.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}

Food Control | TFG UAH

{% endblock %}

{% block style %}

body
{
padding-top: 40px;
padding-bottom: 40px;
background-color: #eee;
    padding-left: 70px;

}

{% endblock %}






{% block content %}


<div  class="col-sm-3 col-lg-offset-4 " class="container-fluid " >
    <h2> Bienvenido:  {{ user_name }}</h2>
    <p> Para activar su cuenta pulse el siguiente link <a href='{{ link }}'> Activa tu Cuenta</a></p>


</div>




{% endblock %}

templates/activation_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<p class='lead'>{% trans "Your account is now activated." %}</p>
{% endblock %}

templates/charts.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap %}
{% load bootstrap3 %}
{% load i18n %}
{% load tz %}

{% block title %}


Food Control | TFG UAH

{% endblock %}
{% block javascript %}
<script>
$( window ).load(function() {
    $("#ir_a").click(function (e) {

        if($("#id_idSemana").val()===''){
            swal({type:'error',title:'Food Control', html:'Rellene el campo semana',})
            e.preventDefault();
        }else{
            $("#week").val($("#id_idSemana").val())

        }
    })

});
function dashboard(id, fData){
    var barColor = 'steelblue';
    function segColor(c){ return {low:"#807dba", mid:"#e08214",high:"#41ab5d"}[c]; }

    // compute total for each state.
    fData.forEach(function(d){d.total=d.freq.low+d.freq.mid+d.freq.high;});

    // function to handle histogram.
    function histoGram(fD){
        var hG={},    hGDim = {t: 60, r: 0, b: 30, l: 0};
        hGDim.w = 500 - hGDim.l - hGDim.r,
        hGDim.h = 300 - hGDim.t - hGDim.b;

        //create svg for histogram.



        var hGsvg = d3.select(id).append("svg")
            .attr("width", hGDim.w + hGDim.l + hGDim.r)
            .attr("height", hGDim.h + hGDim.t + hGDim.b).append("g")
            .attr("transform", "translate(" + hGDim.l + "," + hGDim.t + ")");



        // create function for x-axis mapping.
        console.log()
        var x = d3.scale.ordinal().rangeRoundBands([0, hGDim.w], 0.1)
                .domain(fD.map(function(d) { return d[0]; }));

        // Add x-axis to the histogram svg.
        hGsvg.append("g").attr("class", "x axis")
            .attr("transform", "translate(0," + hGDim.h + ")")
            .call(d3.svg.axis().orient("bottom").scale(x)

            );

        // Create function for y-axis map.
        var y = d3.scale.linear().range([hGDim.h, 0])
                .domain([0, d3.max(fD, function(d) { return d[1]; })]);

        // Create bars for histogram to contain rectangles and freq labels.
        var bars = hGsvg.selectAll(".bar").data(fD).enter()
                .append("g").attr("class", "bar");

        //create the rectangles.
        bars.append("rect")
            .attr("x", function(d) { return x(d[0]); })
            .attr("y", function(d) { return y(d[1]); })
            .attr("width", x.rangeBand())
            .attr("height", function(d) { return hGDim.h - y(d[1]); })
            .attr('fill',barColor)
            .on("mouseover",mouseover)// mouseover is defined below.
            .on("mouseout",mouseout);// mouseout is defined below.

        //Create the frequency labels above the rectangles.
        bars.append("text").text(function(d){ return d3.format(",")(d[1])})
            .attr("x", function(d) { return x(d[0])+x.rangeBand()/2; })
            .attr("y", function(d) { return y(d[1])-5; })
            .attr("text-anchor", "middle");

        function mouseover(d){  // utility function to be called on mouseover.
            // filter for selected state.
            }

        function mouseout(d){    // utility function to be called on mouseout.

        }

        // create function to update the bars. This will be used by pie-chart.
        hG.update = function(nD, color){
            // update the domain of the y-axis map to reflect change in frequencies.
            y.domain([0, d3.max(nD, function(d) { return d[1]; })]);

            // Attach the new data to the bars.
            var bars = hGsvg.selectAll(".bar").data(nD);

            // transition the height and color of rectangles.
            bars.select("rect").transition().duration(500)
                .attr("y", function(d) {return y(d[1]); })
                .attr("height", function(d) { return hGDim.h - y(d[1]); })
                .attr("fill", color);

            // transition the frequency labels location and change value.
            bars.select("text").transition().duration(500)
                .text(function(d){ return d3.format(",")(d[1])})
                .attr("y", function(d) {return y(d[1])-5; });
        }
        return hG;
    }

    // function to handle pieChart.


    // function to handle legend.

    // calculate total frequency by segment for all state.
    var tF = ['low','mid','high'].map(function(d){
        return {type:d, freq: d3.sum(fData.map(function(t){ return t.freq[d];}))};
    });

    // calculate total frequency by state for all segment.
    var sF = fData.map(function(d){return [d.State,d.total];});

    var hG = histoGram(sF) // create the histogram.

}
</script>

<script>




var freqData={{ chart|safe}}
var freqData2 ={{ glucosa|safe }}
dashboard('#dashboard',freqData);
dashboard('#dashboard2',freqData2);
</script>



{% endblock %}
{% block style %}


path {  stroke: #fff; }
path:hover {  opacity:0.9; }
rect:hover {  fill:blue; }
.axis {  font: 10px sans-serif; }
.legend tr{    border-bottom:1px solid grey; }
.legend tr:first-child{    border-top:1px solid grey; }

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.x.axis path {  display: none; }
.legend{
    margin-bottom:76px;
    display:inline-block;
    border-collapse: collapse;
    border-spacing: 0px;
}
.legend td{
    padding:4px 5px;
    vertical-align:bottom;
}
.legendFreq, .legendPerc{
    align:right;
    width:50px;
}


{% endblock %}

{% block content %}

    <nav style="margin-left: 10%"  class="  navbar navbar-default-2  ">
{% if request.user.is_staff %}

    {% endif %}

        <div id="navbar" class="navbar-collapse collapse">

            <ul class="nav navbar-nav">



                </ul>

            <ul  class="nav navbar-nav navbar-right">
                    <li>
                        <p style="color:white;"> Período desde : {{ dias_inicio }}  </p>

                    </li>
                    <li>
                         <p style="color:white; padding-left: 10px; word-spacing: 10px">   hasta {{ dias_final }}</p>
                    </li>

                   <li>
                    <p  style="color: white; margin-left: 10px; margin-right: 10px;"> Semana: <a style="color: #1b7b34"  class="text-center" >{{ form }} </a>
                        <button form="progreso"  id="ir_a" class="btn  btn-primary btn-xs" name="ir_a" type="submit" style="margin-right: 0;  background-color: transparent;border: transparent">
                            <span class="glyphicon glyphicon-search"></span></button>
                    </p>
                       </li>

                    <li><button form="progreso" class="btn  btn-primary btn-xs"  name="retroceder" type="submit" style="padding-right: 0px; background-color: transparent;border: transparent">
                        <span class="glyphicon glyphicon-arrow-left" ></span>
                        </button>
                    </li>
                    <li><button form="progreso" class="btn  btn-primary btn-xs" name="avanzar" type="submit" style="padding-right: 10px;  background-color: transparent;border: transparent">
                     <span class="glyphicon glyphicon-arrow-right"></span>
                    </button>
                    </li>


            </ul>

            <form id="progreso" method="post" action="{% url 'progreso_nutricional' username=user  %}"> {% csrf_token %}
                <input type="hidden" id="week" name="week" value="{{ semana }}">
                <input type="hidden" name="week_2" value="{{ semana }}">
            </form>

            <ul class="nav navbar-nav navbar-left ">
                <p style="color:white;"> Paciente: {{ user.first_name }} {{ user.last_name }} </p>
            </ul>


        </div><!--/.nav-collapse -->

</nav>


    {% if diabetes %}



        <div class=""  style="margin-left: 10%; float: left; text-align: center;" id='dashboard'>
            <h2 >Calorías registradas</h2>
        </div>

        <div class=""  style="margin-left: 5%; float: left;text-align: center;" id='dashboard2'>
            <h2 >Índice de Glucosa</h2>
        </div>
    {% else %}
        <div class=""  style="text-align: center"  id='dashboard'>
            <h2 >Calorías registradas</h2>
        </div>


    {% endif %}









{% endblock %}

templates/informacion.html
{% extends "base.html" %}
{% load bootstrap %}
{% load bootstrap3 %}

{% block title %}

Food Control | TFG UAH

{% endblock%}
{% block style %}

    body
    {
        padding : 20px;
        background-color: #eee;
    }


{% endblock %}

{% block content %}

{% block javascript %}
<script>
var incorrect = false
var correct = false
var exist=false
$(window).load(function () {

    $("#register").click(function (e) {

       if(allFilled())
           $("#modificar").submit()




    });

    $('#id_peso').keyup(function(e) {
            var regex = /^\d+(\.\d{0,2})?$/g;
            if (!regex.test(this.value)) {
                this.value = '';
            }
        });
    $('#id_estatura').keyup(function(e) {
            var regex = /^\d+(\.\d{0,2})?$/g;
            if (!regex.test(this.value)) {
                this.value = '';
            }
        });

    /*$("#id_first_name, #id_last_name, #id_username, #id_email,  #id_doctor,  #id_estatura, #id_peso").bind('keyup', function () {
        if (allFilled()) {
            $('#register').prop('disabled', false);

        }else {
            $('#register').prop('disabled', true);
        }
    });*/
});



function allFilled() {
    var filled = true;
    $('body input').each(function() {
        if($(this).val() == '') {
            $(this).parent().parent().addClass('form-group has-error has-feedback');

            filled = false;
        }

    });
    return filled;
}










</script>
{% endblock %}
    {% include "messages.html" %}

    <div class="container-fluid">
        <form id="modificar" method="post" action="{% url 'informacion' %}">

            {% csrf_token %}
            <div id="info" class="  form-group form-group-sm">
                <h1 class="lead"> Datos Personales</h1>
                <table class="table table-condensed">
                    {% for field in form %}
                    <tr>

                        <td>

                            {{ field|bootstrap_horizontal }}


                    {% endfor %}
                        </td>
                    </tr>


                    <br>
                </table>
                <div class="submit-row col-sm-4" >
                    <input  id="register"class="btn  btn-primary active btn-xs " type="button" value="Modificar"/></td></tr>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

templates/messages.html
{% if messages %}


    {% for message in messages %}
        {% if message.tags == "success" %}

            <script>
                var texto = '{{ message }}'
                texto = texto.replace("&lt;i&gt;","<i>")
                texto = texto.replace("&lt;/i&gt;","</i>")
                texto = texto.replace("&lt;br&gt;", "<br/>")

                swal({type:'success',title:'Food Control', html:texto});
            </script>


        {% endif %}
        {% if message.tags == "error" %}
            <script>

            swal({type:'error',title:'Food Control', html:'{{ message }}',});


            </script>

        {% endif %}

    {% endfor %}

{% endif %}

templates/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap %}
{% load bootstrap3 %}
{% block title %}

Food Control | TFG UAH

{% endblock %}

{% block style %}

body
{
padding-top: 40px;
padding-bottom: 40px;
background-color: #eee;
    padding-left: 70px;

}

{% endblock %}

{% block content %}




<div style="margin-left:20%;padding-top: 7%; "  class="col-md-offset-2 container-fluid " >
    {% include "messages.html" %}
<div style="position: relative">
<div style="width:35%; padding: 0;" class="col-lg-offset-2  panel panel-default ">
    <div style="  background: #337ab7; border-bottom-color: #337ab7; color:#ffffff; text-align: center;" class="panel-heading">Cambiar Contraseña</div>
        <form id="prueba" class=" form-group form-group-md "  action="{% url 'change_password' %}" method="POST" >
            {% csrf_token %} 
            <div class="col-lg-12" style=" margin-top: 2%;margin-bottom: 2%;" >
                <div class="form-group">
                <div >
            <label class="control-label" for="id_password">Password:</label>
            <input id="id_password" name="password" type="password"  class="form-control"  placeholder="Password" required="true">
             </div>
                    </div>
                <div class="form-group">
                <div>
            <label class="control-label" for="id_re_password">Re-Password:</label>
            <input  id="id_re_password" name="re_password" type="password" class="form-control"  placeholder="Re-Password" required="true">
                    </div>
                    <br>
            <input  style="margin-left: 35%;" class="col-sm-offset-4 btn btn-sm btn-primary" id="Continuar" type="submit" value="Continuar"/>

            </div>
                </div>
            <br>
            <a style="margin-left: 40%; color: #222" class="btn btn-link btn-xs col-sm-offset-3" href="" ></a>
            <input name="username" type="hidden" value="{{ username }}">
         </form>

</div>




</div>









{% endblock %}

templates/password_reset_email.html
 {% extends "base.html" %}
{% load bootstrap %}

{% block title %}

Food Control | TFG UAH

{% endblock %}

{% block style %}

body
{
padding-top: 40px;
padding-bottom: 40px;
background-color: #eee;
    padding-left: 70px;

}

{% endblock %}






{% block content %}



<div  class="col-sm-3 col-lg-offset-4 " class="container-fluid " >
    <h2> Buenas  {{ user_name }}</h2>
    <br>
    <p>Estas recibiendo este correo porque has solicitado reestablecer tu password para tu cuenta en Food Conterol
    <a href='{{ link }}'> Restablece tu contraseña</a></p>


</div>




{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load bootstrap %}
{% load bootstrap3 %}

{% block title %}

Food Control | TFG UAH

{% endblock%}
{% block style %}

    body
    {
        margin-top : 20px;
        background-color: #eee;
    }


{% endblock %}

{% block content %}

{% block javascript %}
<script>
var incorrect = false
var correct = false
var exist=false
$("#id_first_name, #id_last_name, #id_username, #id_email, #id_password, #id_doctor, #id_genero, #id_estatura, #id_peso, #id_diabetico, #id_re_password").bind('keyup', function() {
    if(allFilled()) {
        var username =   $("#id_username").val()
        $.ajax({
        type:"POST",
        url: "{% url 'validate_username' %}",
        data: {
            'username': username,
            'csrfmiddlewaretoken':"{{ csrf_token }}"
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken===false) {
              if(correct==false ) {
                  $("#id_username").parent().parent().removeClass().addClass('form-group has-success has-feedback');
                  if ($("#id_password").parent().parent().attr('class')=='form-group has-success has-feedback')
                      $('#register').prop('disabled',false);
                  exist=false


              }

          }else{
              if(incorrect==false) {

                  $("#id_username").parent().parent().addClass(' has-error has-feedback');
                  $('#register').prop('disabled',true);
                  swal({
                        type:'error',
                        title:'Oops',
                        html:'<a>El Usuario '+'<strong>'+username+'</strong>' + ' ya existe </a>'

                         }
                        )



              }


          }
        },
        error:function(exception){
            console.log(exception)
            alert('Exeption:'+exception);
            event.preventDefault();

        }
      });



    }
});

function allFilled() {
    var filled = true;
    $('body input').each(function() {
        if($(this).val() == '') filled = false;

    });
    return filled;
}



$(document).ready(function() {
  $("#id_re_password").keyup(validate);
});




function validate() {
    var password1 = $("#id_password").val();
    var password2 = $("#id_re_password").val();
    var error=false;
    var succes=false;
    alert



    if (password1 == password2) {
        if (error) {


            $("#id_password").parent().parent().removeClass().addClass('form-group has-success has-feedback');
            $("#id_re_password").parent().parent().removeClass().addClass('form-group has-success has-feedback');
            if (correct)
                $("#register").prop('disabled',false);

            error=false
        }else{

            $("#id_password").parent().parent().removeClass().addClass('form-group has-success has-feedback');
            $("#id_re_password").parent().parent().removeClass().addClass('form-group has-success has-feedback');
            if (correct)
                $("#register").prop('disabled',false);
            succes=true

        }

    }else {
        if (succes){

            $( "#id_password" ).parent().parent().removeClass().addClass('form-group has-error has-feedback');
            $( "#id_re_password" ).parent().parent().removeClass().addClass('form-group has-error has-feedback');
            $("#register").prop('disabled',true);
            succes=false
        }  else{

             $( "#id_password" ).parent().parent().removeClass().addClass('form-group has-error has-feedback');
            $( "#id_re_password" ).parent().parent().removeClass().addClass('form-group has-error has-feedback');
            $("#register").prop('disabled',true);
            error=true


        }

    }
}





</script>
{% endblock %}
    {% include "messages.html" %}

    <div class="container-fluid main">
        <form id="signup" method="post" action="{% url 'signup' %}">

            {% csrf_token %}
            <div class="  form-group form-group-sm">
                <h1 class="lead"> Alta Usuario</h1>
                <table class="table table-condensed">
                    {% for field in form %}
                    <tr>

                        <td>

                            {{ field|bootstrap_horizontal }}


                    {% endfor %}
                        </td>
                    </tr>


                    <br>
                </table>
                <div class="submit-row col-sm-4" >
                    <input  id="register" disabled="true" class="btn  btn-primary btn-xs active" type="submit" value="Registrarse"/></td></tr>
                </div>
            </div>
        </form>
    </div>

{% endblock %}